<?php

// src/AppBundle/DataFixtures/ORM/LoadUserGroupData.php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use AppBundle\Entity\Country;

class CountryDF extends AbstractFixture implements OrderedFixtureInterface {

    public function load(ObjectManager $manager) {

        $temp = array(
            array('country_code' => 'US', 'country_name' => 'Stany Zjednoczone Ameryki', 'seq' => '0',),
            array('country_code' => 'UK', 'country_name' => 'Wielka Brytania', 'seq' => '0',),
            array('country_code' => 'NO', 'country_name' => 'Norwegia', 'seq' => '0',),
            array('country_code' => 'GR', 'country_name' => 'Grecja', 'seq' => '0',),
            array('country_code' => 'AF', 'country_name' => 'Afganistan', 'seq' => '0',),
            array('country_code' => 'AL', 'country_name' => 'Albania', 'seq' => '0',),
            array('country_code' => 'DZ', 'country_name' => 'Algieria', 'seq' => '0',),
            array('country_code' => 'AS', 'country_name' => 'Samoa', 'seq' => '0',),
            array('country_code' => 'AD', 'country_name' => 'Andora', 'seq' => '0',),
            array('country_code' => 'AO', 'country_name' => 'Angola', 'seq' => '0',),
            array('country_code' => 'AI', 'country_name' => 'Anguilla', 'seq' => '0',),
            array('country_code' => 'AG', 'country_name' => 'Antigua i Barbuda', 'seq' => '0',),
            array('country_code' => 'AN', 'country_name' => 'Antyle, Holenderskie', 'seq' => '0',),
            array('country_code' => 'AR', 'country_name' => 'Argentyna', 'seq' => '0',),
            array('country_code' => 'AM', 'country_name' => 'Armenia', 'seq' => '0',),
            array('country_code' => 'AW', 'country_name' => 'Aruba', 'seq' => '0',),
            array('country_code' => 'AU', 'country_name' => 'Australia', 'seq' => '0',),
            array('country_code' => 'AT', 'country_name' => 'Austria', 'seq' => '0',),
            array('country_code' => 'AZ', 'country_name' => 'Azerbejdżan', 'seq' => '0',),
            array('country_code' => 'BS', 'country_name' => 'Bahamy', 'seq' => '0',),
            array('country_code' => 'BH', 'country_name' => 'Bahrajn', 'seq' => '0',),
            array('country_code' => 'BD', 'country_name' => 'Bangladesz', 'seq' => '0',),
            array('country_code' => 'BB', 'country_name' => 'Barbados', 'seq' => '0',),
            array('country_code' => 'BY', 'country_name' => 'Białoruś', 'seq' => '0',),
            array('country_code' => 'BE', 'country_name' => 'Belgia', 'seq' => '0',),
            array('country_code' => 'BZ', 'country_name' => 'Belize', 'seq' => '0',),
            array('country_code' => 'BJ', 'country_name' => 'Benin', 'seq' => '0',),
            array('country_code' => 'BM', 'country_name' => 'Bermudy', 'seq' => '0',),
            array('country_code' => 'BT', 'country_name' => 'Bhutan', 'seq' => '0',),
            array('country_code' => 'BO', 'country_name' => 'Boliwia', 'seq' => '0',),
            array('country_code' => 'BA', 'country_name' => 'Bośnia i Hercegowina', 'seq' => '0',),
            array('country_code' => 'BW', 'country_name' => 'Botswana', 'seq' => '0',),
            array('country_code' => 'BR', 'country_name' => 'Brazylia', 'seq' => '0',),
            array('country_code' => 'VG', 'country_name' => 'Brytyjskie Wyspy Dziewicze', 'seq' => '0',),
            array('country_code' => 'BN', 'country_name' => 'Brunei', 'seq' => '0',),
            array('country_code' => 'BG', 'country_name' => 'Bułgaria', 'seq' => '0',),
            array('country_code' => 'BF', 'country_name' => 'Burkina Faso', 'seq' => '0',),
            array('country_code' => 'BI', 'country_name' => 'Burundi', 'seq' => '0',),
            array('country_code' => 'KH', 'country_name' => 'Kambodża', 'seq' => '0',),
            array('country_code' => 'CM', 'country_name' => 'Kamerun', 'seq' => '0',),
            array('country_code' => 'CA', 'country_name' => 'Kanada', 'seq' => '0',),
            array('country_code' => 'CV', 'country_name' => 'Republika Zielonego Przylądka', 'seq' => '0',),
            array('country_code' => 'KY', 'country_name' => 'Kajmany', 'seq' => '0',),
            array('country_code' => 'CF', 'country_name' => 'Republika Środkowoafrykańska', 'seq' => '0',),
            array('country_code' => 'TD', 'country_name' => 'Czad', 'seq' => '0',),
            array('country_code' => 'CL', 'country_name' => 'Chile', 'seq' => '0',),
            array('country_code' => 'CN', 'country_name' => 'Chiny', 'seq' => '0',),
            array('country_code' => 'CO', 'country_name' => 'Kolumbia', 'seq' => '0',),
            array('country_code' => 'KM', 'country_name' => 'Komory', 'seq' => '0',),
            array('country_code' => 'CG', 'country_name' => 'Kongo', 'seq' => '0',),
            array('country_code' => 'CD', 'country_name' => 'Republika Demokratyczna Konga', 'seq' => '0',),
            array('country_code' => 'CK', 'country_name' => 'Wyspy Cooka', 'seq' => '0',),
            array('country_code' => 'CR', 'country_name' => 'Kostaryka', 'seq' => '0',),
            array('country_code' => 'CI', 'country_name' => 'Wybrzeże Kości Słoniowej', 'seq' => '0',),
            array('country_code' => 'HR', 'country_name' => 'Chorwacja', 'seq' => '0',),
            array('country_code' => 'CU', 'country_name' => 'Cuba', 'seq' => '0',),
            array('country_code' => 'CY', 'country_name' => 'Cyprus', 'seq' => '0',),
            array('country_code' => 'CZ', 'country_name' => 'Czech Republic', 'seq' => '0',),
            array('country_code' => 'DK', 'country_name' => 'Dania', 'seq' => '0',),
            array('country_code' => 'DJ', 'country_name' => 'Dżibuti', 'seq' => '0',),
            array('country_code' => 'DM', 'country_name' => 'Dominika', 'seq' => '0',),
            array('country_code' => 'DO', 'country_name' => 'Dominikana', 'seq' => '0',),
            array('country_code' => 'TP', 'country_name' => 'Timor Wschodni', 'seq' => '0',),
            array('country_code' => 'EC', 'country_name' => 'Ekwador', 'seq' => '0',),
            array('country_code' => 'EG', 'country_name' => 'Egipt', 'seq' => '0',),
            array('country_code' => 'SV', 'country_name' => 'Salwador', 'seq' => '0',),
            array('country_code' => 'GQ', 'country_name' => 'Gwinea Równikowa', 'seq' => '0',),
            array('country_code' => 'ER', 'country_name' => 'Erytrea', 'seq' => '0',),
            array('country_code' => 'EE', 'country_name' => 'Estonia', 'seq' => '0',),
            array('country_code' => 'ET', 'country_name' => 'Etiopia', 'seq' => '0',),
            array('country_code' => 'FK', 'country_name' => 'Falklandy', 'seq' => '0',),
            array('country_code' => 'FO', 'country_name' => 'Wyspy Owcze', 'seq' => '0',),
            array('country_code' => 'FJ', 'country_name' => 'Fidżi', 'seq' => '0',),
            array('country_code' => 'FI', 'country_name' => 'Finlandia', 'seq' => '0',),
            array('country_code' => 'FR', 'country_name' => 'Francja', 'seq' => '0',),
            array('country_code' => 'GF', 'country_name' => 'Gujana Francuska', 'seq' => '0',),
            array('country_code' => 'PF', 'country_name' => 'Polinezja Francuska', 'seq' => '0',),
            array('country_code' => 'GA', 'country_name' => 'Gabon', 'seq' => '0',),
            array('country_code' => 'GM', 'country_name' => 'Gambia', 'seq' => '0',),
            array('country_code' => 'GE', 'country_name' => 'Gruzja', 'seq' => '0',),
            array('country_code' => 'DE', 'country_name' => 'Niemcy', 'seq' => '0',),
            array('country_code' => 'GH', 'country_name' => 'Ghana', 'seq' => '0',),
            array('country_code' => 'GI', 'country_name' => 'Gibraltar', 'seq' => '0',),
            array('country_code' => 'GL', 'country_name' => 'Grenlandia', 'seq' => '0',),
            array('country_code' => 'GD', 'country_name' => 'Grenada', 'seq' => '0',),
            array('country_code' => 'GP', 'country_name' => 'Gwadelupa', 'seq' => '0',),
            array('country_code' => 'GU', 'country_name' => 'Guam', 'seq' => '0',),
            array('country_code' => 'GT', 'country_name' => 'Gwatemala', 'seq' => '0',),
            array('country_code' => 'GG', 'country_name' => 'Guernsey i Alderney', 'seq' => '0',),
            array('country_code' => 'GN', 'country_name' => 'Gwinea', 'seq' => '0',),
            array('country_code' => 'GW', 'country_name' => 'Gwinea Bissau', 'seq' => '0',),
            array('country_code' => 'GP', 'country_name' => 'Gwinea, Równikowa', 'seq' => '0',),
            array('country_code' => 'GF', 'country_name' => 'Gujana Francuska', 'seq' => '0',),
            array('country_code' => 'GY', 'country_name' => 'Gujana', 'seq' => '0',),
            array('country_code' => 'HT', 'country_name' => 'Haiti', 'seq' => '0',),
            array('country_code' => 'HN', 'country_name' => 'Honduras', 'seq' => '0',),
            array('country_code' => 'HK', 'country_name' => 'Hong Kong (Chiny)', 'seq' => '0',),
            array('country_code' => 'HU', 'country_name' => 'Węgry', 'seq' => '0',),
            array('country_code' => 'IS', 'country_name' => 'Islandia', 'seq' => '0',),
            array('country_code' => 'IN', 'country_name' => 'Indie', 'seq' => '0',),
            array('country_code' => 'ID', 'country_name' => 'Indonezja', 'seq' => '0',),
            array('country_code' => 'IR', 'country_name' => 'Iran', 'seq' => '0',),
            array('country_code' => 'IQ', 'country_name' => 'Irak', 'seq' => '0',),
            array('country_code' => 'IE', 'country_name' => 'Irlandia', 'seq' => '0',),
            array('country_code' => 'IL', 'country_name' => 'Izrael', 'seq' => '0',),
            array('country_code' => 'CI', 'country_name' => 'Wybrzeże Kości Słoniowej', 'seq' => '0',),
            array('country_code' => 'IT', 'country_name' => 'Włochy', 'seq' => '0',),
            array('country_code' => 'JM', 'country_name' => 'Jamajka', 'seq' => '0',),
            array('country_code' => 'JP', 'country_name' => 'Japonia', 'seq' => '0',),
            array('country_code' => 'JE', 'country_name' => 'Jersey', 'seq' => '0',),
            array('country_code' => 'JO', 'country_name' => 'Jordania', 'seq' => '0',),
            array('country_code' => 'KZ', 'country_name' => 'Kazachstan', 'seq' => '0',),
            array('country_code' => 'KE', 'country_name' => 'Kenia', 'seq' => '0',),
            array('country_code' => 'KI', 'country_name' => 'Kiribati', 'seq' => '0',),
            array('country_code' => 'KR', 'country_name' => 'Korea Południowa', 'seq' => '0',),
            array('country_code' => 'KW', 'country_name' => 'Kuwejt', 'seq' => '0',),
            array('country_code' => 'KG', 'country_name' => 'Kirgistan', 'seq' => '0',),
            array('country_code' => 'LA', 'country_name' => 'Korea Północna', 'seq' => '0',),
            array('country_code' => 'LV', 'country_name' => 'Łotwa', 'seq' => '0',),
            array('country_code' => 'LB', 'country_name' => 'Liban', 'seq' => '0',),
            array('country_code' => 'LS', 'country_name' => 'Lesotho', 'seq' => '0',),
            array('country_code' => 'LY', 'country_name' => 'Libia', 'seq' => '0',),
            array('country_code' => 'LI', 'country_name' => 'Lichtenstein', 'seq' => '0',),
            array('country_code' => 'LT', 'country_name' => 'Litwa', 'seq' => '0',),
            array('country_code' => 'LU', 'country_name' => 'Luksemburg', 'seq' => '0',),
            array('country_code' => 'MO', 'country_name' => 'Makau (Chiny)', 'seq' => '0',),
            array('country_code' => 'MK', 'country_name' => 'Macedonia', 'seq' => '0',),
            array('country_code' => 'MG', 'country_name' => 'Madagaskar', 'seq' => '0',),
            array('country_code' => 'MW', 'country_name' => 'Malawi', 'seq' => '0',),
            array('country_code' => 'MY', 'country_name' => 'Malezja', 'seq' => '0',),
            array('country_code' => 'MV', 'country_name' => 'Malediwy', 'seq' => '0',),
            array('country_code' => 'ML', 'country_name' => 'Mali', 'seq' => '0',),
            array('country_code' => 'MT', 'country_name' => 'Malta', 'seq' => '0',),
            array('country_code' => 'MQ', 'country_name' => 'Martynika', 'seq' => '0',),
            array('country_code' => 'MR', 'country_name' => 'Mauretania', 'seq' => '0',),
            array('country_code' => 'MU', 'country_name' => 'Mauritius', 'seq' => '0',),
            array('country_code' => 'MX', 'country_name' => 'Meksyk', 'seq' => '0',),
            array('country_code' => 'FM', 'country_name' => 'Mikronezja', 'seq' => '0',),
            array('country_code' => 'MD', 'country_name' => 'Mołdawia, Republika', 'seq' => '0',),
            array('country_code' => 'MC', 'country_name' => 'Monako', 'seq' => '0',),
            array('country_code' => 'MN', 'country_name' => 'Mongolia', 'seq' => '0',),
            array('country_code' => 'CS', 'country_name' => 'Czarnogóra', 'seq' => '0',),
            array('country_code' => 'MA', 'country_name' => 'Maroko', 'seq' => '0',),
            array('country_code' => 'MZ', 'country_name' => 'Mozambik', 'seq' => '0',),
            array('country_code' => 'MM', 'country_name' => 'Myanmar (dawniej Birma)', 'seq' => '0',),
            array('country_code' => 'NA', 'country_name' => 'Namibia', 'seq' => '0',),
            array('country_code' => 'NP', 'country_name' => 'Nepal', 'seq' => '0',),
            array('country_code' => 'NL', 'country_name' => 'Holandia', 'seq' => '0',),
            array('country_code' => 'NC', 'country_name' => 'Nowa Kaledonia', 'seq' => '0',),
            array('country_code' => 'NZ', 'country_name' => 'Nowa Zelandia', 'seq' => '0',),
            array('country_code' => 'NI', 'country_name' => 'Nikaragua', 'seq' => '0',),
            array('country_code' => 'NE', 'country_name' => 'Niger', 'seq' => '0',),
            array('country_code' => 'NG', 'country_name' => 'Nigeria', 'seq' => '0',),
            array('country_code' => 'MP', 'country_name' => 'Mariany Północne', 'seq' => '0',),
            array('country_code' => 'OM', 'country_name' => 'Oman', 'seq' => '0',),
            array('country_code' => 'PK', 'country_name' => 'Pakistan', 'seq' => '0',),
            array('country_code' => 'PS', 'country_name' => 'Palestyna', 'seq' => '0',),
            array('country_code' => 'PA', 'country_name' => 'Panama', 'seq' => '0',),
            array('country_code' => 'PG', 'country_name' => 'Papua-Nowa Gwinea', 'seq' => '0',),
            array('country_code' => 'PY', 'country_name' => 'Paragwaj', 'seq' => '0',),
            array('country_code' => 'PE', 'country_name' => 'Peru', 'seq' => '0',),
            array('country_code' => 'PH', 'country_name' => 'Filipiny', 'seq' => '0',),
            array('country_code' => 'PL', 'country_name' => 'Polska', 'seq' => '0',),
            array('country_code' => 'PT', 'country_name' => 'Portugalia', 'seq' => '0',),
            array('country_code' => 'QA', 'country_name' => 'Katar', 'seq' => '0',),
            array('country_code' => 'RE', 'country_name' => 'Reunion', 'seq' => '0',),
            array('country_code' => 'RO', 'country_name' => 'Rumunia', 'seq' => '0',),
            array('country_code' => 'RU', 'country_name' => 'Rosja', 'seq' => '0',),
            array('country_code' => 'RW', 'country_name' => 'Rwanda', 'seq' => '0',),
            array('country_code' => 'KN', 'country_name' => 'Saint Kitts i Nevis', 'seq' => '0',),
            array('country_code' => 'LC', 'country_name' => 'Saint Lucia', 'seq' => '0',),
            array('country_code' => 'VC', 'country_name' => 'St.Vincent i Grenadyny', 'seq' => '0',),
            array('country_code' => 'WS', 'country_name' => 'Samoa', 'seq' => '0',),
            array('country_code' => 'SM', 'country_name' => 'San Marino', 'seq' => '0',),
            array('country_code' => 'ST', 'country_name' => 'Wyspy Św.Tomasza i Książęca', 'seq' => '0',),
            array('country_code' => 'SA', 'country_name' => 'Arabia Saudyjska', 'seq' => '0',),
            array('country_code' => 'SN', 'country_name' => 'Senegal', 'seq' => '0',),
            array('country_code' => 'RS', 'country_name' => 'Serbia', 'seq' => '0',),
            array('country_code' => 'SC', 'country_name' => 'Seszele', 'seq' => '0',),
            array('country_code' => 'SG', 'country_name' => 'Singapur', 'seq' => '0',),
            array('country_code' => 'SK', 'country_name' => 'Słowacja', 'seq' => '0',),
            array('country_code' => 'SI', 'country_name' => 'Slowenia', 'seq' => '0',),
            array('country_code' => 'SB', 'country_name' => 'Wyspy Salomona', 'seq' => '0',),
            array('country_code' => 'SO', 'country_name' => 'Somalia', 'seq' => '0',),
            array('country_code' => 'ES', 'country_name' => 'Hiszpania', 'seq' => '0',),
            array('country_code' => 'LK', 'country_name' => 'Sri Lanka', 'seq' => '0',),
            array('country_code' => 'SD', 'country_name' => 'Sudan', 'seq' => '0',),
            array('country_code' => 'SR', 'country_name' => 'Surinam', 'seq' => '0',),
            array('country_code' => 'SZ', 'country_name' => 'Suazi', 'seq' => '0',),
            array('country_code' => 'SE', 'country_name' => 'Szwecja', 'seq' => '0',),
            array('country_code' => 'CH', 'country_name' => 'Szwajcaria', 'seq' => '0',),
            array('country_code' => 'SY', 'country_name' => 'Syria', 'seq' => '0',),
            array('country_code' => 'TW', 'country_name' => 'Tajwan', 'seq' => '0',),
            array('country_code' => 'TJ', 'country_name' => 'Tadżykistan', 'seq' => '0',),
            array('country_code' => 'TZ', 'country_name' => 'Tanzania', 'seq' => '0',),
            array('country_code' => 'TH', 'country_name' => 'Tajlandia', 'seq' => '0',),
            array('country_code' => 'TG', 'country_name' => 'Togo', 'seq' => '0',),
            array('country_code' => 'TO', 'country_name' => 'Tonga', 'seq' => '0',),
            array('country_code' => 'TT', 'country_name' => 'Trynidad i Tobago', 'seq' => '0',),
            array('country_code' => 'TN', 'country_name' => 'Tunezja', 'seq' => '0',),
            array('country_code' => 'TR', 'country_name' => 'Turcja', 'seq' => '0',),
            array('country_code' => 'TM', 'country_name' => 'Turkmenistan', 'seq' => '0',),
            array('country_code' => 'UG', 'country_name' => 'Uganda', 'seq' => '0',),
            array('country_code' => 'UA', 'country_name' => 'Ukraina', 'seq' => '0',),
            array('country_code' => 'AE', 'country_name' => 'Zjedn.Emiraty Arabskie', 'seq' => '0',),
            array('country_code' => 'UY', 'country_name' => 'Urugwaj', 'seq' => '0',),
            array('country_code' => 'UZ', 'country_name' => 'Uzbekistan', 'seq' => '0',),
            array('country_code' => 'VU', 'country_name' => 'Vanuatu', 'seq' => '0',),
            array('country_code' => 'VE', 'country_name' => 'Wenezuela', 'seq' => '0',),
            array('country_code' => 'VN', 'country_name' => 'Wietnam', 'seq' => '0',),
            array('country_code' => 'VI', 'country_name' => 'Wyspy Dziewicze-USA', 'seq' => '0',),
            array('country_code' => 'YE', 'country_name' => 'Jemen', 'seq' => '0',),
            array('country_code' => 'ZM', 'country_name' => 'Zambia', 'seq' => '0',),
            array('country_code' => 'ZW', 'country_name' => 'Zimbabwe', 'seq' => '0',),
        );

        foreach ($temp as $t2) {
            $country = new Country();
            $country->setCountryCode($t2['country_code']);
            $country->setCountryName($t2['country_name']);
            $country->setSeq($t2['seq']);
            $manager->persist($country);

            $this->setReference('country_' . $t2['country_code'], $country); //ustawienie referencji by mozna było powiązać i przypisac w userach 
        }
        $manager->flush();
    }

    public function getOrder() {
        return 0;
    }

}
